### ISSUE TITLE
Error getting reporting units

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#130]
```
elex reporting-units 2012-11-06

Traceback (most recent call last):
  File "/Users/jbowers/.virtualenvs/elex-loader/bin/elex", line 9, in <module>
    load_entry_point('elex==0.0.42', 'console_scripts', 'elex')()
  File "/Users/jbowers/.virtualenvs/elex-loader/src/nyt-ap-elections/elex/cli/app.py", line 155, in main
    app.run()
  File "/Users/jbowers/.virtualenvs/elex-loader/lib/python2.7/site-packages/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/Users/jbowers/.virtualenvs/elex-loader/lib/python2.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/jbowers/.virtualenvs/elex-loader/src/nyt-ap-elections/elex/cli/decorators.py", line 13, in decorated
    return fn(self)
  File "/Users/jbowers/.virtualenvs/elex-loader/src/nyt-ap-elections/elex/cli/app.py", line 73, in reporting_units
    self.app.render(self.app.election.reporting_units)
  File "/Users/jbowers/.virtualenvs/elex-loader/lib/python2.7/site-packages/cement/core/foundation.py", line 829, in render
    out_text = self.output.render(data, template)
  File "/Users/jbowers/.virtualenvs/elex-loader/src/nyt-ap-elections/elex/cli/ext_csv.py", line 25, in render
    writer.writerow(row.serialize().values())
  File "/Users/jbowers/.virtualenvs/elex-loader/src/nyt-ap-elections/elex/parser/api.py", line 509, in serialize
    ('votecount', self.votecount),
AttributeError: 'ReportingUnit' object has no attribute 'votecount'```

**Comment by jeremyjbowers** [comment]
Some never got their votecount set -- fixed in sha 2e416f6aba0dfde6bae9b14230f7f88c083272fb and sha 38d671f209f22e23f453073d132bc29e84c5605f
