### ISSUE TITLE
Error in 3/5 results

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex#228]
```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/elex-loader/bin/elex", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/cli/app.py", line 260, in main
    app.run()
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/cli/decorators.py", line 50, in decorated
    return fn(self)
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/cli/decorators.py", line 19, in decorated
    return fn(self)
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/cli/app.py", line 104, in reporting_units
    data = self.app.election.reporting_units
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/api/models.py", line 981, in reporting_units
    race_objs = self.get_race_objects(raw_races)
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/api/models.py", line 902, in get_race_objects
    return [Race(**r) for r in parsed_json['races']]
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/api/models.py", line 617, in __init__
    self.set_new_england_counties()
  File "/home/ubuntu/.virtualenvs/elex-loader/local/lib/python2.7/site-packages/elex/api/models.py", line 645, in set_new_england_counties
    ru_name = maps.FIPS_TO_STATE[ru.statepostal][ru.fipscode]
KeyError: u'00023'
```

**Comment by greglinch** [comment]
I've also experienced this. Thanks for tackling!
